name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout &c. here
      - uses: ./.github/actions/test@v1

      - name: Build package
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          PUBLIC_URL: /bjcp-viewer
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: build
